name: Deploy estate-bot

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          extensions: mbstring, intl, pdo_mysql, bcmath, curl, zip
          coverage: none

      - name: Install Composer deps (prod)
        run: |
          composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader

      # Если позже будет Vite — здесь setup-node + npm ci && npm run build

      - name: Set release name
        run: echo "RELEASE_NAME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Rsync files to server (new release)
        uses: appleboy/rsync-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./"
          target: "${{ secrets.DEPLOY_PATH }}/releases/${{ env.RELEASE_NAME }}/"
          # важные параметры rsync:
          args: >
            --archive
            --compress
            --delete
            --human-readable
            --itemize-changes
            --exclude ".git"
            --exclude "node_modules"
            --exclude "tests"
            --exclude ".github"

      - name: Activate release on server
        uses: appleboy/ssh-action@v1.2.0
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          RELEASE_NAME: ${{ env.RELEASE_NAME }}
          PHP_BIN: ${{ secrets.PHP_BIN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            set -e

            DEPLOY_PATH="${DEPLOY_PATH:-$HOME/apps/estate-bot}"
            PHP_BIN="${PHP_BIN:-php}"
            REL_DIR="$DEPLOY_PATH/releases/$RELEASE_NAME"

            # shared links
            ln -sfn "$DEPLOY_PATH/shared/.env" "$REL_DIR/.env"

            rm -rf "$REL_DIR/storage"
            ln -sfn "$DEPLOY_PATH/shared/storage" "$REL_DIR/storage"

            mkdir -p "$DEPLOY_PATH/shared/bootstrap/cache"
            ln -sfn "$DEPLOY_PATH/shared/bootstrap/cache" "$REL_DIR/bootstrap/cache"

            cd "$REL_DIR"

            # оптимизация и миграции
            $PHP_BIN artisan key:generate --force || true
            $PHP_BIN artisan storage:link || true

            $PHP_BIN artisan config:cache
            $PHP_BIN artisan route:cache || true
            $PHP_BIN artisan view:cache || true

            $PHP_BIN artisan migrate --force || true

            # атомарное переключение current
            ln -sfn "$REL_DIR" "$DEPLOY_PATH/current"

            chmod -R ug+rw "$DEPLOY_PATH/shared/storage" "$DEPLOY_PATH/shared/bootstrap/cache" || true

            echo "✅ Deployed $RELEASE_NAME"
