name: Deploy estate-bot

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer:v2
          extensions: mbstring, intl, pdo_mysql, bcmath, curl, zip
          coverage: none

      - name: Install Composer deps (prod)
        run: |
          composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader

      - name: Set release name
        run: echo "RELEASE_NAME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Add known_hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Rsync to server (new release)
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          RELEASE_NAME: ${{ env.RELEASE_NAME }}
        run: |
          : ${SSH_PORT:=22}
          rsync -az --delete \
            --exclude ".git" \
            --exclude ".github" \
            --exclude "node_modules" \
            --exclude "tests" \
            -e "ssh -p ${SSH_PORT}" ./ \
            "${SSH_USER}@${SSH_HOST}:${DEPLOY_PATH}/releases/${RELEASE_NAME}/"

      - name: Activate release on server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
          SSH_USER: ${{ secrets.SSH_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          RELEASE_NAME: ${{ env.RELEASE_NAME }}
          PHP_BIN: ${{ secrets.PHP_BIN }}
        run: |
          : ${SSH_PORT:=22}
          : ${PHP_BIN:=php}

          ssh -p ${SSH_PORT} ${SSH_USER}@${SSH_HOST} bash << EOSSH
          set -e
          DEPLOY_PATH="${DEPLOY_PATH:-/home/${SSH_USER}/apps/estate-bot}"
          REL_DIR="\$DEPLOY_PATH/releases/${RELEASE_NAME}"

          ln -sfn "\$DEPLOY_PATH/shared/.env" "\$REL_DIR/.env"
          rm -rf "\$REL_DIR/storage"
          ln -sfn "\$DEPLOY_PATH/shared/storage" "\$REL_DIR/storage"
          mkdir -p "\$DEPLOY_PATH/shared/bootstrap/cache"
          ln -sfn "\$DEPLOY_PATH/shared/bootstrap/cache" "\$REL_DIR/bootstrap/cache"

          cd "\$REL_DIR"

          ${PHP_BIN} artisan key:generate --force || true
          ${PHP_BIN} artisan storage:link || true
          ${PHP_BIN} artisan config:cache
          ${PHP_BIN} artisan route:cache || true
          ${PHP_BIN} artisan view:cache || true
          ${PHP_BIN} artisan migrate --force || true

          ln -sfn "\$REL_DIR" "\$DEPLOY_PATH/current"
          chmod -R ug+rw "\$DEPLOY_PATH/shared/storage" "\$DEPLOY_PATH/shared/bootstrap/cache" || true

          echo "✅ Deployed ${RELEASE_NAME}"
          EOSSH
