name: Deploy estate-bot (self-hosted)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: [ self-hosted, linux, estate-prod ]   # тот лейбл, что задал при config.sh
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: PHP info
        run: php -v

      - name: Prepare release dir
        run: |
          export DEPLOY_PATH="$HOME/apps/estate-bot"
          export RELEASE_NAME=$(date +'%Y%m%d%H%M%S')
          echo "RELEASE_NAME=$RELEASE_NAME" >> $GITHUB_ENV
          mkdir -p "$DEPLOY_PATH/releases/$RELEASE_NAME" "$DEPLOY_PATH/shared/storage" "$DEPLOY_PATH/shared/bootstrap/cache"
          rsync -a --delete --exclude=".git" --exclude=".github" --exclude="node_modules" --exclude="tests" ./ "$DEPLOY_PATH/releases/$RELEASE_NAME/"

      - name: Link shared & optimize & migrate
        run: |
          export DEPLOY_PATH="$HOME/apps/estate-bot"
          export RELEASE_NAME="${{ env.RELEASE_NAME }}"
          export REL_DIR="$DEPLOY_PATH/releases/$RELEASE_NAME"

          ln -sfn "$DEPLOY_PATH/shared/.env" "$REL_DIR/.env"
          rm -rf "$REL_DIR/storage"
          ln -sfn "$DEPLOY_PATH/shared/storage" "$REL_DIR/storage"
          ln -sfn "$DEPLOY_PATH/shared/bootstrap/cache" "$REL_DIR/bootstrap/cache"

          cd "$REL_DIR"
          composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader || true
          php artisan key:generate --force || true
          php artisan storage:link || true
          php artisan config:cache
          php artisan route:cache || true
          php artisan view:cache || true
          php artisan migrate --force || true

          ln -sfn "$REL_DIR" "$DEPLOY_PATH/current"
          chmod -R ug+rw "$DEPLOY_PATH/shared/storage" "$DEPLOY_PATH/shared/bootstrap/cache" || true

          echo "✅ Deployed $RELEASE_NAME"
